name: 'TestStatus'
on:
  push: 
    branches: 
      - master
jobs:
  testing_repository:
    runs-on: ubuntu-latest
    steps:
      - name: git clone my repository
        uses: actions/checkout@v1
        
      - name: install packages
        run: npm install
        
      - name: testing(JEST)
        run: npx jest
  
